Repository Parallel-Gaming-Studio/AirportBunchesOfFun, pull requests merged in 2020-05, with the labels that each got.

#31 Structure and Dependency Changes
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/loader.js
Labels: testing needed

#33 Dusty
  docs/includes/start_scene.html
  docs/scripts/game_manager.js
  docs/scripts/scene_start.js
  docs/styles/styles.css
Labels: bug, testing needed

#35 Fixed Game Scale Issue
  docs/scripts/engine.js
  docs/scripts/game.js
  docs/scripts/scene_start.js
Labels: bug, testing needed

#36 Removed Debuggers
  docs/scripts/engine.js
  docs/scripts/scene_start.js
Labels: bug, testing needed

#37 Testing Needed
  docs/includes/end_scene.html
  docs/includes/reusables.html
  docs/includes/start_scene.html
  docs/scripts/game_manager.js
  docs/scripts/scene_end.js
Labels: bug, testing needed

#43 Start Scene Button Update
  docs/includes/db_admin.php
  docs/scripts/scene_start.js
Labels: bug, testing needed

#42 Allen
  docs/images/play_timer.png
  docs/includes/end_scene.html
  docs/scripts/game_manager.js
  docs/scripts/scene_end.js
  docs/styles/styles.css
Labels: bug, testing needed

#45 Instantiatable Timer Class
  docs/index.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/jquery-3.4.1.min.js
  docs/scripts/jquery-3.5.1.js
  docs/scripts/jquery-3.5.1.min.js
  docs/scripts/jquery.js
  docs/scripts/jquery_activity.js
  docs/scripts/jquery_nav.js
  docs/scripts/loader.js
  docs/scripts/timer.js
Labels: enhancement, testing needed

#39 Havens
  docs/images/sponsors/sponsor_cibo_express.png
  docs/includes/leaderboard_scene.html
  docs/includes/reusables.html
  docs/scripts/game.js
  docs/scripts/game_manager.js
  docs/scripts/scene_leaderboard.js
  docs/styles/Lato-Medium.ttf
  docs/styles/SIL Open Font License.txt
  docs/styles/styles.css
Labels: documentation, testing needed

#46 Overlay Fixes
  docs/styles/styles.css
Labels: bug, testing needed

#44 Play Scene Update
  docs/includes/leaderboard_scene.html
  docs/includes/play_scene.html
  docs/scripts/game_manager.js
  docs/scripts/loader.js
  docs/scripts/scene_end.js
  docs/scripts/scene_leaderboard.js
  docs/scripts/scene_play.js
Labels: testing needed
